python src/train.py \
    --input_file data/argumented_subtaskB_train.jsonl \
    --model roberta-large \
    --lr 2e-5 \
    --epoch 2 \
    --frac_warmup 0.1 \
    --gradient_accumulations 8 \
    --batch_size 8 \
    --num_workers 16\
    --alpha 0.9 \
    --precision bf16-mixed \
    --weight_decay 0.01 \
